import {removeFromBlocking, removeFromPending, removeFromUploadStarted} from "./util";

/**
 * Manage response of file upload requests
 *
 * @since 1.8.0
 *
 * @param {object} response generated by hashFile() => createMediaFromFile()
 * @param {object} cf2 fields config with status set
 * @param {object} $form object
 * @param {object} messages to be passed for different responses
 * @param {object] field we are processing files for
 */
export const handleFileUploadResponse = (response,cf2,$form,messages,field) => {

	const {fieldId} = field;
	if( 'object' !== typeof  response ){
		removeFromUploadStarted(fieldId,cf2);
		removeFromPending(fieldId,cf2);
		throw 'Upload Error';
	}
	else if (response.hasOwnProperty('control')) {
		removeFromPending(fieldId,cf2);
		removeFromBlocking(fieldId,cf2);
		cf2.uploadCompleted.push(fieldId);
		$form.submit();
	}else{
		if( response.hasOwnProperty('message') ){
			messages[field.fieldIdAttr] = {
				error: true,
				message: response.hasOwnProperty('message') ? response.message : 'Invalid'
			};
		}
		removeFromUploadStarted(fieldId,cf2);
		removeFromPending(fieldId,cf2);
		throw response;
	}
};

export  const handleFileUploadError = (error) => {

};
